DjangoAccountBoilerplate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
]

accounts/urls.py
from django.urls import path

from .views import home, register, login_user, logout_user

app_name = 'accounts'
urlpatterns = [
    path('', home, name='home'),
    path('login', login_user, name='login'),
    path('register', register, name='register'),
    path('logout', logout_user, name="logout"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Diabetes Prediction</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">Diabetes Prediction</a>
        <div class="d-flex gap-3">
{% if request.user.is_authenticated %}
<a
class="btn btn-outline-success"
href="{% url 'accounts:logout' %}"
>
Logout
</a>
{% else %}
<a
class="btn btn-outline-success"
href="{% url 'accounts:register' %}"
>
Register
</a>
<a class="btn btn-outline-success" href="{% url 'accounts:login' %}"
>Login</a
>
{% endif %}
     
        </div>
      </div>
    </nav>

    <main class="d-flex justify-content-center">
      {% block content %} {% endblock content %}
    </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
  </body>
</html>